#!/bin/bash
# This file is scripts/install_dependencies.sh

yum update
yum install -y python3 python3-pip unzip
ls
unzip -o /site.zip -d /home/ec2-user
pip3 install -r /home/ec2-user/requirements.txt
